config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  root to: 'public/homes#top'
  get '/about', to: 'public/homes#about'

  namespace :public do
    resources :customers, only: %i[show edit update]
    # ユーザーの過去の投稿一覧画面
    get '/customers/:id/post_all', to: 'customers#post_all', as: 'customers_post_all'
    # ユーザーのコメントをした投稿一覧画面
    get '/customer/:id/post_comment_all', to: 'customers#post_comment_all', as: 'customers_post_comment_all'
    # ユーザーの過去の投稿一覧画面での検索結果表示画面
    get '/customers/:id/post_search', to: 'customers#post_search', as: 'customers_post_search'
    resources :posts do
      resources :post_comments, only: %i[edit update create destroy]
    end
    # 検索フォームでの検索結果表示画面
    get '/word_search', to: 'posts#word_search'
    # タグ別表示画面
    get '/tag_search', to: 'posts#tag_search'
    # カテゴリー別表示画面
    get '/posts/category_search/:id', to: 'posts#category_search', as: 'posts_category_search'
    # 通知一覧画面
    resources :notifications, only: %i[index]
    # 通知全削除
    delete '/notifications', to: 'notifications#destroy_all', as: 'notifications_destroy_all'
    # お問い合わせ
    resources :contacts, only: %i[new create]
    # お問い合わせ内容確認画面
    post '/contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    # お問い合わせ確認画面から入力内容をそのままにしてフォームに戻す
    post '/contacts/back', to: 'contacts#back', as: 'back'
    # お問い合わせ完了画面
    get '/contacts/complete', to: 'contacts#complete', as: 'complete'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { maximum: 500 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # 通知機能のアソシエーション
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 100 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true
  # ユーザー(customer)とのアソシエーション
  belongs_to :visitor, class_name: 'Customer', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'Customer', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :post_image

  has_many :post_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  belongs_to :customer, optional: true
  belongs_to :category, optional: true

  validates :category_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = tags.pluck(:name) unless tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      tags << new_post_tag
    end
  end

  # コメント通知メソッド
  def create_notification_post_comment!(current_customer, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:customer_id).where(post_id: id).where.not(customer_id: current_customer.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_customer, post_comment_id, temp_id['customer_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_customer, post_comment_id, customer_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_customer, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_customer.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  attachment :comment_image

  has_many :notifications, dependent: :destroy

  belongs_to :customer
  belongs_to :post

  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  # 投稿とタグの中間テーブル
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 新規登録後
  def after_sign_up_path_for(_resource)
    flash[:notice] = '新規ユーザー登録しました'
    root_path
  end

  # ログイン後
  def after_sign_in_path_for(_resource)
    flash[:notice] = '　ログインしました　'
    root_path
  end

  # ログアウト後
  def after_sign_out_path_for(_resource)
    flash[:notice] = '　ログアウトしました　'
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name introduction profile_image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning error-message">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewEmployee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body id="page-top">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light mt-4">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand text-white", style: "text-decoration: none;" do %>
            <h2>NewEmployee</h2>
          <% end %>
          <%= form_with url: public_word_search_path, method: :get, local: true do |f| %>
            <div class="input-group word-search">
              <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "form-control" %>
              <span class="input-group-append">
                <%= button_tag type: 'submit', class: "btn btn-outline-secondary text-white" do %>
                  <i class="fas fa-search"></i>
                <% end %>
              </span>
            </div>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li><%= link_to 'マイページ', public_customer_path(current_customer.id), class:"nav-link text-white mr-2" %></li>
                <% if unchecked_notifications.any? %>
                  <span class="fa fa-circle mt-2" style="color: yellow;"></span>
                <% end %>
                <li><%= link_to "通知", public_notifications_path, class: "btn-default text-white mt-2 pb-2 mr-2" %></li>
                <li><%= link_to '投稿する', new_public_post_path, class: "nav-link text-white" %></li>
                <li><%= link_to '投稿一覧', public_posts_path, class: "nav-link text-white" %></li>
                <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-white" %></li>
              <% else %>
                <li><%= link_to '投稿一覧', public_posts_path, class: "nav-link text-white" %></li>
                <li><%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-white" %></li>
                <li><%= link_to "ログイン", new_customer_session_path, class: "nav-link text-white" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="openbtn"><span></span><span></span><span></span></div>
    <nav id="g-nav">
      <div id="g-nav-list"><!--ナビの数が増えた場合縦スクロールするためのdiv※不要なら削除-->
        <ul>
          <% if customer_signed_in? %>
            <li class="menu-btn-icon"><%= link_to "", public_customer_path(current_customer.id), class: "fas fa-user-cog text-white", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">マイページ</li>
            <li class="mt-3 menu-btn-icon"><%= link_to "", new_public_post_path, class: "fas fa-edit text-white", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">投稿する</li>
            <li class="mt-3"><%= link_to "", public_posts_path, class: "far fa-comments text-white", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">投稿を見る</li>
          <% else %>
            <li><%= link_to '', public_posts_path, class: "nav-link text-white far fa-comments", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">投稿を見る</li>
            <li class="mt-3 menu-btn-icon"><%= link_to "", new_customer_registration_path, class: "nav-link text-white fas fa-user-plus", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">ユーザー登録</li>
            <li class="mt-3"><%= link_to "", new_customer_session_path, class: "nav-link text-white far fa-sign-in-alt", style: "font-size: 40px" %></li>
            <li class="menu-btn-text">ログイン</li>
          <% end %>
        </ul>
      </div>
    </nav>
    <script>
      $(".openbtn").click(function () {//ボタンがクリックされたら
    	  $(this).toggleClass('active');//ボタン自身に activeクラスを付与し
        $("#g-nav").toggleClass('panelactive');//ナビゲーションにpanelactiveクラスを付与
      });

      $("#g-nav a").click(function () {//ナビゲーションのリンクがクリックされたら
        $(".openbtn").removeClass('active');//ボタンの activeクラスを除去し
        $("#g-nav").removeClass('panelactive');//ナビゲーションのpanelactiveクラスも除去
      });
    </script>
    <p class="pagetop" style="display: block;">
      <a href="#page-top">
        <i class="fas fa-chevron-up"></i>
      </a>
    </p>
    <p class="pagebottom" style="display: block;">
      <a href="#page-bottom">
        <i class="fas fa-chevron-down"></i>
      </a>
    </p>
    <%= yield %>
    <div id ="page-bottom"></div>
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="footer-logo col-12"><%= link_to "NewEmployee", root_path, class: "text-white" %></div><br>
          <div class="footer-nav mt-3">
            <%= link_to "About", about_path, class: "text-white" %>
            <%= link_to "お問い合わせ", new_public_contact_path, class: "text-white mx-3" %>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>